// Code generated by protoc-gen-custom. DO NOT EDIT.
package v1

import (
	"github.com/gin-gonic/gin"
	"github.com/zngue/zng_app/pkg/router"
)

type AdFormHTTPServer interface 
type AdFormHTTPServer interface {
	// AddAdd  新增
	Add(*gin.Context, *GetTestRequest) (*GetTestReply, error)
}
func RegisterAdFormHTTPServer(s *gin.RouterGroup, srv AdFormHTTPServer) []router.IRouter {
func RegisterAdFormHTTPServer(s *gin.RouterGroup, srv AdFormHTTPServer)[]router.IRouter {
	group := s.Group("/")
	return router.ApiServiceFn(
		router.ApiGetFn(group, "/v1/adForm/add", _AdForm_Add0_HTTP_Handler(srv)),
	)
func _AdForm_Add0_HTTP_Handler(srv AdFormHTTPServer) router.Fn {
func _AdForm_Add0_HTTP_Handler(srv AdFormHTTPServer) router.Fn  {
	return func(ctx *gin.Context) (rs any, err error) {
		var in *GetTestRequest
		if err = ctx.BindJSON(&in); err != nil {
			return
		}
		rs, err = srv.Add(ctx, in)
		return
	}
}

type TestGinHttpService struct {
}

// 6666
// /v1/test/info

func (s *TestGinHttpService) Info(ctx *gin.Context) (req *GetTestRequest, err error) {
	req = new(GetTestRequest)
	err = ctx.BindJSON(&req)
	return

}

// 6666
// /v1/test/list

func (s *TestGinHttpService) List(ctx *gin.Context) (req *GetListTestRequest, err error) {
	req = new(GetListTestRequest)
	err = ctx.BindJSON(&req)
	return

}
