package main

import (
	"fmt"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

func main() {
	opts := &protogen.Options{}
	opts.Run(func(gen *protogen.Plugin) error {
		files := gen.Files
		for _, file := range files {
			fileName := file.GeneratedFilenamePrefix + ".gin_http.pb.go"
			g := gen.NewGeneratedFile(fileName, file.GoImportPath)
			g.P("// Code generated by protoc-gen-custom. DO NOT EDIT.")
			g.P("package ", file.GoPackageName)
			g.P()
			//import
			g.P("import (")
			g.P("\"github.com/gin-gonic/gin\"")
			g.P(")")
			for _, service := range file.Services {
				var httpServiceName = fmt.Sprintf("%sGinHttpService", service.Desc.Name())
				g.P(fmt.Sprintf("type %s struct {", httpServiceName))
				g.P("}")
				for _, method := range service.Methods {
					//获取请求路由

					httpOption := method.Desc.Options()
					extension := proto.GetExtension(httpOption, annotations.E_Http)
					httpRule := extension.(*annotations.HttpRule)
					if httpRule == nil {
						continue
					}
					url := ""
					url = httpRule.GetPost()
					if url == "" {
						url = httpRule.GetGet()
					}
					g.P(fmt.Sprintf("// %s", url))
					g.P(fmt.Sprintf("func (s *%s) %s(ctx *gin.Context)    {", httpServiceName, method.GoName))
					//g.P(fmt.Sprintf(httpGetTemplate,
					//	httpServiceName,
					//	method.GoName,
					//	method.Input.GoIdent.GoName,
					//	method.Input.GoIdent.GoName,
					//))
					g.P("}")
				}
			}

		}
		return nil
	})
}

const httpRequestTemplate = `
func (s *%s) %s(ctx *gin.Context)  (req *%s,err error) {
	 req = new(%s)
	 err = ctx.%s(&req)
	 return
`
const fnTemplates = `
func _{{serverName}}_{{method}}_GIN_HTTP_Handler(srv {{serverName}}TTPServer) router.Fn  {
	return func(ctx *gin.Context) (rs any, err error) {
		var in *{{inName}}
		if err = ctx.BindJSON(&in); err != nil {
			return
		}
		rs, err = srv.{{method}}(ctx, in)
		return
	}
}
`

func BindParamsFn(isGet bool) {

}

func BindParams(isGet bool, httpServiceName, goName, inputGoName string) string {
	if isGet {
		return fmt.Sprintf(httpRequestTemplate,
			httpServiceName,
			goName,
			inputGoName,
			inputGoName,
			"BindJSON",
		)
	} else {
		return fmt.Sprintf(httpRequestTemplate,
			httpServiceName,
			goName,
			inputGoName,
			inputGoName,
			"BindJSON",
		)
	}
}

/**


var e_http=&protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         72295728,
		Name:          "google.api.http",
		Tag:           "bytes,72295728,opt,name=http",
		Filename:      "google/api/annotations.proto",
	}
*/
